# Generated by Django 5.2.4 on 2025-07-29 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Bullet point or sub-item content')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_included', models.BooleanField(default=True, help_text='Whether this sub-item is included in the current version')),
                ('section_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='resumes.sectionitem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
